go get github.com/docker/docker/api 
go get github.com/docker/docker/api/types 
go get github.com/docker/docker/api/types/blkiodev 
go get github.com/docker/docker/api/types/container 
go get github.com/docker/docker/api/types/events 
go get github.com/docker/docker/api/types/filters 
go get github.com/docker/docker/api/types/image 
go get github.com/docker/docker/api/types/mount 
go get github.com/docker/docker/api/types/network 
go get github.com/docker/docker/api/types/registry 
go get github.com/docker/docker/api/types/strslice 
go get github.com/docker/docker/api/types/swarm 
go get github.com/docker/docker/api/types/swarm/runtime 
go get github.com/docker/docker/api/types/time 
go get github.com/docker/docker/api/types/versions 
go get github.com/docker/docker/api/types/volume 
go get github.com/docker/docker/client 
go get github.com/docker/docker/vendor/github.com/docker/distribution/digestset 
go get github.com/docker/docker/vendor/github.com/docker/distribution/reference 
go get github.com/docker/docker/vendor/github.com/docker/go-connections/nat 
go get github.com/docker/docker/vendor/github.com/docker/go-connections/sockets 
go get github.com/docker/docker/vendor/github.com/docker/go-connections/tlsconfig 
go get github.com/docker/docker/vendor/github.com/docker/go-units 
go get github.com/docker/docker/vendor/github.com/gogo/protobuf/proto 
go get github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go 
go get github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1 
go get github.com/docker/docker/vendor/github.com/pkg/errors 
go get github.com/docker/docker/vendor/golang.org/x/net/context 
go get github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp 
go get github.com/docker/docker/vendor/golang.org/x/net/proxy 
go get github.com/go-chi/chi 
go get github.com/go-chi/chi/middleware 
go get github.com/gorilla/securecookie 
go get github.com/jhoonb/archivex 
go get github.com/jinzhu/gorm 
go get github.com/jinzhu/inflection 
go get github.com/mattn/go-sqlite3 
go get github.com/mkreder/dockerpanel/controller 
go get github.com/mkreder/dockerpanel/login 
go get github.com/mkreder/dockerpanel/model 
go get github.com/mkreder/dockerpanel/templates 
go get github.com/mkreder/dockerpanel/tools 
go get github.com/mkreder/dockerpanel/worker 
go get github.com/opencontainers/go-digest 
go get github.com/valyala/bytebufferpool 
go get github.com/valyala/quicktemplate 
go get golang.org/x/crypto/bcrypt 
go get golang.org/x/crypto/blowfish 
go get golang.org/x/net/context 
