// This file is automatically generated by qtc from "ftp.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/ftp.qtpl:1
package templates

//line templates/ftp.qtpl:1
import "github.com/mkreder/dockerpanel/model"

//line templates/ftp.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/ftp.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/ftp.qtpl:2
func StreamFtpTemplate(qw422016 *qt422016.Writer, uftps []model.UsuarioFTP, webs []model.Web, ftpConfig model.FtpConfig, error string) {
	//line templates/ftp.qtpl:2
	qw422016.N().S(`

<!DOCTYPE html>
<html lang="en">
<script type="text/javascript">
    var timeoutVar;

    function activarTimeout() {
        timeoutVar = setTimeout(function() {
            window.location.href = window.location.href;
        }, 5000);
    }
    activarTimeout()

    function desactivarTimeout() {
        clearTimeout(timeoutVar);
    }

    function validateForm() {
        var x = document.getElementById("dominio").value;
        if (x == "" ) {
            alert("Se debe elegir el dominio");
            return false;
        }

        var y = document.getElementById("nombre").value;
        if (y == "" ) {
            alert("Se debe completar el nombre de usuario");
            return false;
        }

        var z = document.getElementById("password").value;
        if ( document.getElementById("password").getAttribute("disabled") == "disabled" ){
            } else {
            if (z == "" ) {
                alert("Se debe completar la contraseña");
                return false;
            }
        }

    }

    function generarPassword() {
        if ( document.getElementById("password").getAttribute("disabled") == "disabled" ) {
            document.getElementById("btngenerar").innerHTML="Generar";
            document.getElementById("password").removeAttribute("disabled")
            document.getElementById("checkmostrar").removeAttribute("disabled");
        } else {
            document.getElementById("password").value = Math.random().toString(36).slice(-8);
        }
    }

    function mostrarPassword() {
        if ( document.getElementById('checkmostrar').checked ) {
            document.getElementById('password').removeAttribute("type")
        } else {
            document.getElementById('password').setAttribute("type","password")
        }

    }


    function showDiv() {
        var x = document.getElementById('form');
        x.style.display = 'block';
        desactivarTimeout();
    }


    function hideDiv() {
        var x = document.getElementById('form');
        x.style.display = 'none';
        document.getElementById("nombre").value = "";
        document.getElementById("password").value = "";
        document.getElementById("dominio").options[0].selected = true;
        if ( document.getElementById("password").getAttribute("disabled") == "disabled" ) {
            document.getElementById("btngenerar").innerHTML="Generar";
            document.getElementById("password").removeAttribute("disabled");
            document.getElementById("checkmostrar").removeAttribute("disabled");
        }
        activarTimeout();
    }

    function modifyFtp(id,nombre,dominio) {
        var x = document.getElementById('form');
        document.getElementById("id").value = id;
        document.getElementById("nombre").value = nombre;
        document.getElementById("password").setAttribute("disabled","disabled")
        document.getElementById("btngenerar").innerHTML="Cambiar";
        document.getElementById("checkmostrar").setAttribute("disabled","disabled")

        var seldominio = document.getElementById("dominio");


        for (var i = 0; i < seldominio.options.length; i++) {
            if (seldominio.options[i].value == dominio) {
                seldominio.options[i].selected = true;
            }
        }

        x.style.display = 'block';
        desactivarTimeout();
    }

</script>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Panel Docker</title>

    <!-- Bootstrap Core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="../vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

`)
	//line templates/ftp.qtpl:143
	if len(error) > 0 {
		//line templates/ftp.qtpl:143
		qw422016.N().S(`
<script type="text/javascript">
    window.alert("`)
		//line templates/ftp.qtpl:145
		qw422016.E().S(error)
		//line templates/ftp.qtpl:145
		qw422016.N().S(`")
</script>
`)
		//line templates/ftp.qtpl:147
	}
	//line templates/ftp.qtpl:147
	qw422016.N().S(`

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" >Docker Panel</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="/profile"><i class="fa fa-user fa-fw"></i> Configuración</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->


        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="/"><i class="fa fa-dashboard fa-fw"></i>Principal</a>
                    </li>
                    <li>
                        <a href="/web"><i class="fa fa-server fa-fw"></i>Sitios web</a>
                    </li>
                    <li>
                        <a href="/dns"><i class="fa fa-cloud fa-fw"></i>DNS</a>
                    </li>
                    <li>
                        <a href="/bd"><i class="fa fa-database fa-fw"></i>Bases de datos</a>
                    </li>
                    <li>
                        <a href="/mail"><i class="fa fa-at fa-fw"></i>E-Mail</a>
                    </li>
                    <li>
                        <a href="/ftp"><i class="fa fa-file-archive-o fa-fw"></i>Usuarios FTP</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Usuarios FTP</h4>
                        <button type="button" class="btn pull-right btn-primary btn-sm" onclick="showDiv()">Agregar</button>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Dominio</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>

                            `)
	//line templates/ftp.qtpl:237
	var dominio string
	var id int

	//line templates/ftp.qtpl:239
	qw422016.N().S(`
                            `)
	//line templates/ftp.qtpl:240
	for _, uftp := range uftps {
		//line templates/ftp.qtpl:240
		qw422016.N().S(`

                                `)
		//line templates/ftp.qtpl:242
		for _, web := range webs {
			//line templates/ftp.qtpl:242
			qw422016.N().S(`
                                    `)
			//line templates/ftp.qtpl:243
			if web.ID == uftp.WebID {
				//line templates/ftp.qtpl:243
				qw422016.N().S(`
                                      `)
				//line templates/ftp.qtpl:245
				dominio = web.Dominio
				id = int(web.ID)

				//line templates/ftp.qtpl:247
				qw422016.N().S(`
                                    `)
				//line templates/ftp.qtpl:248
			}
			//line templates/ftp.qtpl:248
			qw422016.N().S(`
                                `)
			//line templates/ftp.qtpl:249
		}
		//line templates/ftp.qtpl:249
		qw422016.N().S(`
                            <tr class="odd gradeX">
                                <td> `)
		//line templates/ftp.qtpl:251
		qw422016.E().S(uftp.Nombre)
		//line templates/ftp.qtpl:251
		qw422016.N().S(` </td>
                                <td> `)
		//line templates/ftp.qtpl:252
		qw422016.E().S(dominio)
		//line templates/ftp.qtpl:252
		qw422016.N().S(` </td>


                                `)
		//line templates/ftp.qtpl:255
		switch uftp.Estado {
		//line templates/ftp.qtpl:256
		case 1:
			//line templates/ftp.qtpl:256
			qw422016.N().S(`
                                <td>a configurar</td>
                                `)
		//line templates/ftp.qtpl:258
		case 2:
			//line templates/ftp.qtpl:258
			qw422016.N().S(`
                                <td>configurado</td>
                                `)
		//line templates/ftp.qtpl:260
		case 3:
			//line templates/ftp.qtpl:260
			qw422016.N().S(`
                                <td>eliminando</td>
                                `)
			//line templates/ftp.qtpl:262
		}
		//line templates/ftp.qtpl:262
		qw422016.N().S(`


                                <td class="center">
                                    <button type="button" class="btn btn-xs btn-primary" data-toggle="tooltip" data-placement="top" title="Modificar usuario de FTP" onclick='modifyFtp(`)
		//line templates/ftp.qtpl:266
		qw422016.N().D(int(uftp.ID))
		//line templates/ftp.qtpl:266
		qw422016.N().S(`, "`)
		//line templates/ftp.qtpl:266
		qw422016.E().S(uftp.Nombre)
		//line templates/ftp.qtpl:266
		qw422016.N().S(`", "`)
		//line templates/ftp.qtpl:266
		qw422016.N().D(int(id))
		//line templates/ftp.qtpl:266
		qw422016.N().S(`" )' ><i class="fa fa-list"></i></button>
                                    <button class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="Eliminar usuario de FTP" onclick="location.href='removeUsuarioFtp?id=`)
		//line templates/ftp.qtpl:267
		qw422016.N().D(int(uftp.ID))
		//line templates/ftp.qtpl:267
		qw422016.N().S(`';"><i class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                            `)
		//line templates/ftp.qtpl:270
	}
	//line templates/ftp.qtpl:270
	qw422016.N().S(`
                            </tbody>
                        </table>
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" onclick="desactivarTimeout()">
                            Configuración
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title" id="myModalLabel">Configuración</h4>
                                    </div>
                                    <form id="ftpconfig" action="/ftpconfig" role=form method="post">
                                        <div class="modal-body">
                                            La siguiente configuración permite definir que permisos tendra el usuario anónimo de FTP sobre un directorio especial reservado para su uso exclusivo.  Este usuario no puede acceder a los directorios de otros usuarios. Puede usarse para permitir que alguien suba o baje archivos sin autentificación.
                                            <br>
                                            <br>
                                            `)
	//line templates/ftp.qtpl:289
	if ftpConfig.AnonRead == 1 {
		//line templates/ftp.qtpl:289
		qw422016.N().S(`
                                                <input name="anonRead" type="checkbox" value="1" checked="checked"> Permiso de lectura
                                            `)
		//line templates/ftp.qtpl:291
	} else {
		//line templates/ftp.qtpl:291
		qw422016.N().S(`
                                                <input name="anonRead" type="checkbox" value="1"> Permiso de lectura
                                            `)
		//line templates/ftp.qtpl:293
	}
	//line templates/ftp.qtpl:293
	qw422016.N().S(`
                                            <br>
                                            `)
	//line templates/ftp.qtpl:295
	if ftpConfig.AnonWrite == 1 {
		//line templates/ftp.qtpl:295
		qw422016.N().S(`
                                                <input name="anonWrite" type="checkbox" value="1" checked="checked"> Permiso de escritura
                                            `)
		//line templates/ftp.qtpl:297
	} else {
		//line templates/ftp.qtpl:297
		qw422016.N().S(`
                                                <input name="anonWrite" type="checkbox" value="1"> Permiso de escritura
                                            `)
		//line templates/ftp.qtpl:299
	}
	//line templates/ftp.qtpl:299
	qw422016.N().S(`

                                        </div>

                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                            <button type="submit" class="btn btn-primary">Guardar</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                        <!-- /.modal -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <div id="form" class="col-lg-6" hidden="true" >
            <div class="panel panel-default">
                <div class="panel-heading">
                    Configuración del Usuario FTP
                </div>
                <div class="panel-body">
                    <form id="addftp" action="/ftp" onsubmit="return validateForm()" role=form method="post">
                        <input id="id" name="id" hidden="true" >
                        <label>Configuración</label>
                        <br>
                        Sitio web
                        <select  class="form-control"  id="dominio" name="dominio">
                            <option disabled selected value> -- Elegir dominio -- </option>
                            `)
	//line templates/ftp.qtpl:336
	for _, web := range webs {
		//line templates/ftp.qtpl:336
		qw422016.N().S(`
                              <option value="`)
		//line templates/ftp.qtpl:337
		qw422016.N().D(int(web.ID))
		//line templates/ftp.qtpl:337
		qw422016.N().S(`">`)
		//line templates/ftp.qtpl:337
		qw422016.E().S(web.Dominio)
		//line templates/ftp.qtpl:337
		qw422016.N().S(`</option>
                            `)
		//line templates/ftp.qtpl:338
	}
	//line templates/ftp.qtpl:338
	qw422016.N().S(`
                        </select>
                        <br>
                        Nombre de usuario
                        <input class="form-control" name="nombre" id="nombre">
                        <br>

                        Contraseña
                        <input class="form-control" name="password" id="password" type="password">
                        <button id="btngenerar" type="button" class="btn btn-default btn-sm" onclick="generarPassword()">Generar</button>
                        <input id="checkmostrar" name="checkmostrar" type="checkbox" value="true" onclick="mostrarPassword()"> Mostrar Contraseña
                        <br>
                        <br>
                        <button type="submit" class="btn btn-default">Guardar</button>
                        <button type="button" class="btn btn-default" onclick="hideDiv()">Cancelar</button>
                    </form>
                </div>
            </div>

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <!--<script src="../vendor/raphael/raphael.min.js"></script>-->
    <!--<script src="../vendor/morrisjs/morris.min.js"></script>-->
    <!--<script src="../data/morris-data.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>

`)
//line templates/ftp.qtpl:384
}

//line templates/ftp.qtpl:384
func WriteFtpTemplate(qq422016 qtio422016.Writer, uftps []model.UsuarioFTP, webs []model.Web, ftpConfig model.FtpConfig, error string) {
	//line templates/ftp.qtpl:384
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/ftp.qtpl:384
	StreamFtpTemplate(qw422016, uftps, webs, ftpConfig, error)
	//line templates/ftp.qtpl:384
	qt422016.ReleaseWriter(qw422016)
//line templates/ftp.qtpl:384
}

//line templates/ftp.qtpl:384
func FtpTemplate(uftps []model.UsuarioFTP, webs []model.Web, ftpConfig model.FtpConfig, error string) string {
	//line templates/ftp.qtpl:384
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/ftp.qtpl:384
	WriteFtpTemplate(qb422016, uftps, webs, ftpConfig, error)
	//line templates/ftp.qtpl:384
	qs422016 := string(qb422016.B)
	//line templates/ftp.qtpl:384
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/ftp.qtpl:384
	return qs422016
//line templates/ftp.qtpl:384
}
