// This file is automatically generated by qtc from "hello.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Hello is a simple template function.

//line hello.qtpl:2
package templates

//line hello.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line hello.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line hello.qtpl:2
func StreamHello(qw422016 *qt422016.Writer, name string) {
	//line hello.qtpl:2
	qw422016.N().S(`
Hello, `)
	//line hello.qtpl:3
	qw422016.E().S(name)
	//line hello.qtpl:3
	qw422016.N().S(`!
`)
//line hello.qtpl:4
}

//line hello.qtpl:4
func WriteHello(qq422016 qtio422016.Writer, name string) {
	//line hello.qtpl:4
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line hello.qtpl:4
	StreamHello(qw422016, name)
	//line hello.qtpl:4
	qt422016.ReleaseWriter(qw422016)
//line hello.qtpl:4
}

//line hello.qtpl:4
func Hello(name string) string {
	//line hello.qtpl:4
	qb422016 := qt422016.AcquireByteBuffer()
	//line hello.qtpl:4
	WriteHello(qb422016, name)
	//line hello.qtpl:4
	qs422016 := string(qb422016.B)
	//line hello.qtpl:4
	qt422016.ReleaseByteBuffer(qb422016)
	//line hello.qtpl:4
	return qs422016
//line hello.qtpl:4
}
