// This file is automatically generated by qtc from "home.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/home.qtpl:1
package templates

//line templates/home.qtpl:1
import "github.com/mkreder/dockerpanel/model"

//line templates/home.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/home.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/home.qtpl:2
func StreamHomeTemplate(qw422016 *qt422016.Writer, containers []model.Container) {
	//line templates/home.qtpl:2
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<script type="text/javascript">
    var timeoutVar;

    function activarTimeout() {
        timeoutVar = setTimeout(function() {
            window.location.href = window.location.href;
        }, 5000);
    }
    activarTimeout()
</script>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Panel Docker</title>

    <!-- Bootstrap Core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="../vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" >Docker Panel</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="/profile"><i class="fa fa-user fa-fw"></i> Configuración</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->


        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="/"><i class="fa fa-dashboard fa-fw"></i>Principal</a>
                    </li>
                    <li>
                        <a href="/web"><i class="fa fa-server fa-fw"></i>Sitios web</a>
                    </li>
                    <li>
                        <a href="/dns"><i class="fa fa-cloud fa-fw"></i>DNS</a>
                    </li>
                    <li>
                        <a href="/bd"><i class="fa fa-database fa-fw"></i>Bases de datos</a>
                    </li>
                    <li>
                        <a href="/mail"><i class="fa fa-at fa-fw"></i>E-Mail</a>
                    </li>
                    <li>
                        <a href="/ftp"><i class="fa fa-file-archive-o fa-fw"></i>Usuarios FTP</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
    <br>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Contenedores</h4>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Imagen</th>
                            <th>Comando</th>
                            <th>Estado</th>
                            <th>Puertos</th>
                        </tr>
                        </thead>
                        <tbody>
                        `)
	//line templates/home.qtpl:138
	for _, container := range containers {
		//line templates/home.qtpl:138
		qw422016.N().S(`
                        <tr class="odd gradeX">
                            <td> `)
		//line templates/home.qtpl:140
		qw422016.E().S(container.ID)
		//line templates/home.qtpl:140
		qw422016.N().S(` </td>
                            <td> `)
		//line templates/home.qtpl:141
		qw422016.E().S(container.Nombre)
		//line templates/home.qtpl:141
		qw422016.N().S(` </td>
                            <td> `)
		//line templates/home.qtpl:142
		qw422016.E().S(container.Imagen)
		//line templates/home.qtpl:142
		qw422016.N().S(` </td>
                            <td> `)
		//line templates/home.qtpl:143
		qw422016.E().S(container.Comando)
		//line templates/home.qtpl:143
		qw422016.N().S(` </td>
                            <td> `)
		//line templates/home.qtpl:144
		qw422016.E().S(container.Estado)
		//line templates/home.qtpl:144
		qw422016.N().S(` </td>
                            <td> `)
		//line templates/home.qtpl:145
		qw422016.E().S(container.Puertos)
		//line templates/home.qtpl:145
		qw422016.N().S(` </td>
                        </tr>
                        `)
		//line templates/home.qtpl:147
	}
	//line templates/home.qtpl:147
	qw422016.N().S(`
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="../vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="../vendor/metisMenu/metisMenu.min.js"></script>

<!-- Morris Charts JavaScript -->
<!--<script src="../vendor/raphael/raphael.min.js"></script>-->
<!--<script src="../vendor/morrisjs/morris.min.js"></script>-->
<!--<script src="../data/morris-data.js"></script>-->

<!-- Custom Theme JavaScript -->
<script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>

`)
//line templates/home.qtpl:183
}

//line templates/home.qtpl:183
func WriteHomeTemplate(qq422016 qtio422016.Writer, containers []model.Container) {
	//line templates/home.qtpl:183
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/home.qtpl:183
	StreamHomeTemplate(qw422016, containers)
	//line templates/home.qtpl:183
	qt422016.ReleaseWriter(qw422016)
//line templates/home.qtpl:183
}

//line templates/home.qtpl:183
func HomeTemplate(containers []model.Container) string {
	//line templates/home.qtpl:183
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/home.qtpl:183
	WriteHomeTemplate(qb422016, containers)
	//line templates/home.qtpl:183
	qs422016 := string(qb422016.B)
	//line templates/home.qtpl:183
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/home.qtpl:183
	return qs422016
//line templates/home.qtpl:183
}
