// This file is automatically generated by qtc from "login.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/login.qtpl:1
package templates

//line templates/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/login.qtpl:1
func StreamLoginTemplate(qw422016 *qt422016.Writer, error string) {
	//line templates/login.qtpl:1
	qw422016.N().S(`

<!DOCTYPE html>
<html lang="en">
<script type="text/javascript">
    function validateForm() {
        var x = document.getElementById("email").value;
        if (x == "" ) {
            alert("Se debe completar el email");
            return false;
        }

        if (/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(x)) {
        } else {
            alert("Email invalido");
            return false;
        }

        var y = document.getElementById("password").value;
        if (y == "" ) {
            alert("Se debe completar el password");
            return false;
        }
    }
</script>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Docker Panel - Login</title>

    <!-- Bootstrap Core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
`)
	//line templates/login.qtpl:59
	if len(error) > 0 {
		//line templates/login.qtpl:59
		qw422016.N().S(`
<script type="text/javascript">
    window.alert("`)
		//line templates/login.qtpl:61
		qw422016.E().S(error)
		//line templates/login.qtpl:61
		qw422016.N().S(`")
</script>
`)
		//line templates/login.qtpl:63
	}
	//line templates/login.qtpl:63
	qw422016.N().S(`
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Inicio de sesión</h3>
                </div>
                <div class="panel-body">
                    <form id="login" action="/login" onsubmit="return validateForm()" role=form method="post">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="E-mail" id="email" name="email" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" id="password" name="password" type="password" value="">
                            </div>
                            <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery -->
<script src="../vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="../vendor/metisMenu/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>
`)
//line templates/login.qtpl:104
}

//line templates/login.qtpl:104
func WriteLoginTemplate(qq422016 qtio422016.Writer, error string) {
	//line templates/login.qtpl:104
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/login.qtpl:104
	StreamLoginTemplate(qw422016, error)
	//line templates/login.qtpl:104
	qt422016.ReleaseWriter(qw422016)
//line templates/login.qtpl:104
}

//line templates/login.qtpl:104
func LoginTemplate(error string) string {
	//line templates/login.qtpl:104
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/login.qtpl:104
	WriteLoginTemplate(qb422016, error)
	//line templates/login.qtpl:104
	qs422016 := string(qb422016.B)
	//line templates/login.qtpl:104
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/login.qtpl:104
	return qs422016
//line templates/login.qtpl:104
}
