// This file is automatically generated by qtc from "web.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/web.qtpl:1
package templates

//line templates/web.qtpl:1
import "github.com/mkreder/dockerpanel/model"

//line templates/web.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/web.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/web.qtpl:2
func StreamWebTemplate(qw422016 *qt422016.Writer, webs []model.Web) {
	//line templates/web.qtpl:2
	qw422016.N().S(`

<!DOCTYPE html>
<html lang="en">
<script type="text/javascript">
    function showDiv() {
        var x = document.getElementById('form');
        x.style.display = 'block';
    }

    function hideDiv() {
        var x = document.getElementById('form');
        x.style.display = 'none';
        document.getElementById("dominio").value = "";
        document.getElementById("ssl").checked = false;
        document.getElementById("cgi").checked = false;
        document.getElementById("python").checked = false;
        document.getElementById("perl").checked = false;
        document.getElementById("php").checked = false;
        document.getElementById("ruby").checked = false;
    }

</script>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Panel Docker</title>

    <!-- Bootstrap Core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="../vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Docker Panel</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="/"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="/web"><i class="fa fa-server fa-fw"></i>Sitios Web</a>
                    </li>
                    <li>
                        <a href="/dns"><i class="fa fa-cloud fa-fw"></i>DNS</a>
                    </li>
                    <li>
                        <a href="/db"><i class="fa fa-database fa-fw"></i>Base de Datos</a>
                    </li>
                    <li>
                        <a href="/mail"><i class="fa fa-at fa-fw"></i>E-Mail</a>
                    </li>
                    <li>
                        <a href="/ftp"><i class="fa fa-file-archive-o fa-fw"></i>FTP</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Sitios Web</h4>
                        <button type="button" class="btn pull-right btn-primary btn-sm" onclick="showDiv()">Agregar</button>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Dominio</th>
                                <th>Estado</th>
                                <th>SSL</th>
                                <th>PHP</th>
                                <th>CGI</th>
                                <th>Python</th>
                                <th>Ruby</th>
                                <th>Perl</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            `)
	//line templates/web.qtpl:149
	for _, web := range webs {
		//line templates/web.qtpl:149
		qw422016.N().S(`
                            <tr class="odd gradeX">
                                <td> `)
		//line templates/web.qtpl:151
		qw422016.E().S(web.Dominio)
		//line templates/web.qtpl:151
		qw422016.N().S(` </td>

                                `)
		//line templates/web.qtpl:153
		switch web.Status {
		//line templates/web.qtpl:154
		case 1:
			//line templates/web.qtpl:154
			qw422016.N().S(`
                                <td>a configurar</td>
                                `)
		//line templates/web.qtpl:156
		case 2:
			//line templates/web.qtpl:156
			qw422016.N().S(`
                                <td>configurado</td>
                                `)
		//line templates/web.qtpl:158
		case 3:
			//line templates/web.qtpl:158
			qw422016.N().S(`
                                <td>corriendo</td>
                                `)
			//line templates/web.qtpl:160
		}
		//line templates/web.qtpl:160
		qw422016.N().S(`

                                `)
		//line templates/web.qtpl:162
		if web.SSL {
			//line templates/web.qtpl:162
			qw422016.N().S(`
                                <td class="center">si</td>
                                `)
			//line templates/web.qtpl:164
		} else {
			//line templates/web.qtpl:164
			qw422016.N().S(`
                                <td class="center">no</td>
                                `)
			//line templates/web.qtpl:166
		}
		//line templates/web.qtpl:166
		qw422016.N().S(`

                                `)
		//line templates/web.qtpl:168
		if web.PHP {
			//line templates/web.qtpl:168
			qw422016.N().S(`
                                <td class="center">si</td>
                                `)
			//line templates/web.qtpl:170
		} else {
			//line templates/web.qtpl:170
			qw422016.N().S(`
                                <td class="center">no</td>
                                `)
			//line templates/web.qtpl:172
		}
		//line templates/web.qtpl:172
		qw422016.N().S(`

                                `)
		//line templates/web.qtpl:174
		if web.CGI {
			//line templates/web.qtpl:174
			qw422016.N().S(`
                                <td class="center">si</td>
                                `)
			//line templates/web.qtpl:176
		} else {
			//line templates/web.qtpl:176
			qw422016.N().S(`
                                <td class="center">no</td>
                                `)
			//line templates/web.qtpl:178
		}
		//line templates/web.qtpl:178
		qw422016.N().S(`

                                `)
		//line templates/web.qtpl:180
		if web.Python {
			//line templates/web.qtpl:180
			qw422016.N().S(`
                                <td class="center">si</td>
                                `)
			//line templates/web.qtpl:182
		} else {
			//line templates/web.qtpl:182
			qw422016.N().S(`
                                <td class="center">no</td>
                                `)
			//line templates/web.qtpl:184
		}
		//line templates/web.qtpl:184
		qw422016.N().S(`

                                `)
		//line templates/web.qtpl:186
		if web.Ruby {
			//line templates/web.qtpl:186
			qw422016.N().S(`
                                <td class="center">si</td>
                                `)
			//line templates/web.qtpl:188
		} else {
			//line templates/web.qtpl:188
			qw422016.N().S(`
                                <td class="center">no</td>
                                `)
			//line templates/web.qtpl:190
		}
		//line templates/web.qtpl:190
		qw422016.N().S(`

                                `)
		//line templates/web.qtpl:192
		if web.Perl {
			//line templates/web.qtpl:192
			qw422016.N().S(`
                                <td class="center">si</td>
                                `)
			//line templates/web.qtpl:194
		} else {
			//line templates/web.qtpl:194
			qw422016.N().S(`
                                <td class="center">no</td>
                                `)
			//line templates/web.qtpl:196
		}
		//line templates/web.qtpl:196
		qw422016.N().S(`


                                <td class="center">
                                    <button type="button" class="btn btn-xs btn-primary"><i class="fa fa-list"></i></button>
                                    <button class="btn btn-xs btn-danger" onclick="location.href='removeWeb?id=`)
		//line templates/web.qtpl:201
		qw422016.N().D(int(web.ID))
		//line templates/web.qtpl:201
		qw422016.N().S(`';"><i class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                            `)
		//line templates/web.qtpl:204
	}
	//line templates/web.qtpl:204
	qw422016.N().S(`
                            </tbody>
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <div id="form" class="col-lg-6" hidden="true" >
            <div class="panel panel-default">
                <div class="panel-heading">
                    Nuevo Sitio
                </div>
                <div class="panel-body">
                    <form id="addweb" action="/addweb" role=form method="post">
                        <label>Dominio</label>
                        <input id="id" name="id" id="dominio" hidden="true" >
                        <input class="form-control" name="dominio" id="dominio">
                        <br>
                        <label>Configuración</label>
                        <div class="checkbox">
                            <label>
                                <input id="ssl" name="ssl" type="checkbox" value="true"> SSL
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="php" name="php" type="checkbox" value="true"> PHP
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="cgi" name="cgi" type="checkbox" value="true"> CGI
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="python" name="python" type="checkbox" value="true"> Python
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="ruby" name="ruby" type="checkbox" value="true"> Ruby
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="perl" name="perl" type="checkbox" value="true"> Perl
                            </label>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-default">Guardar</button>
                        <button type="button" class="btn btn-default" onclick="hideDiv()">Cancelar</button>
                    </form>
                </div>
            </div>

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <!--<script src="../vendor/raphael/raphael.min.js"></script>-->
    <!--<script src="../vendor/morrisjs/morris.min.js"></script>-->
    <!--<script src="../data/morris-data.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>

`)
//line templates/web.qtpl:292
}

//line templates/web.qtpl:292
func WriteWebTemplate(qq422016 qtio422016.Writer, webs []model.Web) {
	//line templates/web.qtpl:292
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/web.qtpl:292
	StreamWebTemplate(qw422016, webs)
	//line templates/web.qtpl:292
	qt422016.ReleaseWriter(qw422016)
//line templates/web.qtpl:292
}

//line templates/web.qtpl:292
func WebTemplate(webs []model.Web) string {
	//line templates/web.qtpl:292
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/web.qtpl:292
	WriteWebTemplate(qb422016, webs)
	//line templates/web.qtpl:292
	qs422016 := string(qb422016.B)
	//line templates/web.qtpl:292
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/web.qtpl:292
	return qs422016
//line templates/web.qtpl:292
}
