// This file is automatically generated by qtc from "zona.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/zona.qtpl:1
package templates

//line templates/zona.qtpl:1
import "github.com/mkreder/dockerpanel/model"

//line templates/zona.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/zona.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/zona.qtpl:2
func StreamZonaTemplate(qw422016 *qt422016.Writer, zonas []model.Zona, error string) {
	//line templates/zona.qtpl:2
	qw422016.N().S(`

<!DOCTYPE html>
<html lang="en">
<script type="text/javascript">
    function validateForm() {
        var x = document.getElementById("dominio").value;
        if (x == "" ) {
            alert("Se debe completar el dominio");
            return false;
        }

        if (/^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9](?:\.[a-zA-Z]{2,})+$/.test(x)) {
        } else {
            alert("Nombre de dominio invalido");
            return false;
        }

        var y = document.getElementById("email").value;
        if (y == "" ) {
            alert("Se debe completar el email");
            return false;
        }

        if (/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(y)) {
        } else {
            alert("Email invalido");
            return false;
        }

    }

    function showDiv() {
        var x = document.getElementById('form');
        x.style.display = 'block';
    }


    function hideDiv() {
        var x = document.getElementById('form');
        x.style.display = 'none';
        document.getElementById("dominio").value = "";
        document.getElementById("email").value = "";
        document.getElementById("id").value = "";
    }

    function modifyZona(id,dominio,email) {
        var x = document.getElementById('form');
        document.getElementById("id").value = id;
        document.getElementById("dominio").value = dominio;
        document.getElementById("email").value = email;
        x.style.display = 'block';
    }

</script>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Panel Docker</title>

    <!-- Bootstrap Core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="../vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

`)
	//line templates/zona.qtpl:93
	if len(error) > 0 {
		//line templates/zona.qtpl:93
		qw422016.N().S(`
<script type="text/javascript">
    window.alert("`)
		//line templates/zona.qtpl:95
		qw422016.E().S(error)
		//line templates/zona.qtpl:95
		qw422016.N().S(`")
</script>
`)
		//line templates/zona.qtpl:97
	}
	//line templates/zona.qtpl:97
	qw422016.N().S(`

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Docker Panel</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="/profile"><i class="fa fa-user fa-fw"></i> Configuración</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="/"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="/web"><i class="fa fa-server fa-fw"></i>Sitios Web</a>
                    </li>
                    <li>
                        <a href="/dns"><i class="fa fa-cloud fa-fw"></i>DNS</a>
                    </li>
                    <li>
                        <a href="/db"><i class="fa fa-database fa-fw"></i>Base de Datos</a>
                    </li>
                    <li>
                        <a href="/mail"><i class="fa fa-at fa-fw"></i>E-Mail</a>
                    </li>
                    <li>
                        <a href="/ftp"><i class="fa fa-file-archive-o fa-fw"></i>FTP</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Zonas</h4>
                        <button type="button" class="btn pull-right btn-primary btn-sm" onclick="showDiv()">Agregar</button>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Dominio</th>
                                <th>Estado</th>
                                <th>E-mail</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            `)
	//line templates/zona.qtpl:182
	for _, zona := range zonas {
		//line templates/zona.qtpl:182
		qw422016.N().S(`
                            <tr class="odd gradeX">
                                <td> `)
		//line templates/zona.qtpl:184
		qw422016.E().S(zona.Dominio)
		//line templates/zona.qtpl:184
		qw422016.N().S(` </td>


                                `)
		//line templates/zona.qtpl:187
		switch zona.Estado {
		//line templates/zona.qtpl:188
		case 1:
			//line templates/zona.qtpl:188
			qw422016.N().S(`
                                <td>a configurar</td>
                                `)
		//line templates/zona.qtpl:190
		case 2:
			//line templates/zona.qtpl:190
			qw422016.N().S(`
                                <td>configurado</td>
                                `)
		//line templates/zona.qtpl:192
		case 3:
			//line templates/zona.qtpl:192
			qw422016.N().S(`
                                <td>corriendo</td>
                                `)
			//line templates/zona.qtpl:194
		}
		//line templates/zona.qtpl:194
		qw422016.N().S(`

                                <td> `)
		//line templates/zona.qtpl:196
		qw422016.E().S(zona.Email)
		//line templates/zona.qtpl:196
		qw422016.N().S(` </td>






                                <td class="center">
                                    <button type="button" class="btn btn-xs btn-primary" onclick='modifyZona(`)
		//line templates/zona.qtpl:204
		qw422016.N().D(int(zona.ID))
		//line templates/zona.qtpl:204
		qw422016.N().S(`, "`)
		//line templates/zona.qtpl:204
		qw422016.E().S(zona.Dominio)
		//line templates/zona.qtpl:204
		qw422016.N().S(`",  "`)
		//line templates/zona.qtpl:204
		qw422016.E().S(zona.Email)
		//line templates/zona.qtpl:204
		qw422016.N().S(`" )' ><i class="fa fa-list"></i></button>
                                    <button class="btn btn-xs btn-info" onclick="location.href='editRegistros?id=`)
		//line templates/zona.qtpl:205
		qw422016.N().D(int(zona.ID))
		//line templates/zona.qtpl:205
		qw422016.N().S(`';"><i class="fa fa-edit"></i></button>
                                    <button class="btn btn-xs btn-danger" onclick="location.href='removeZona?id=`)
		//line templates/zona.qtpl:206
		qw422016.N().D(int(zona.ID))
		//line templates/zona.qtpl:206
		qw422016.N().S(`';"><i class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                            `)
		//line templates/zona.qtpl:209
	}
	//line templates/zona.qtpl:209
	qw422016.N().S(`
                            </tbody>
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <div id="form" class="col-lg-6" hidden="true" >
            <div class="panel panel-default">
                <div class="panel-heading">
                    Nuevo Sitio
                </div>
                <div class="panel-body">
                    <form id="addzona" action="/dns" onsubmit="return validateForm()" role=form method="post">
                        <label>Dominio</label>
                        <input id="id" name="id" id="id" hidden="true" >
                        <input class="form-control" name="dominio" id="dominio">
                        <br>
                        <label>E-mail del administrador</label>
                        <input class="form-control" name="email" id="email">
                        <br>
                        <button type="submit" class="btn btn-default">Guardar</button>
                        <button type="button" class="btn btn-default" onclick="hideDiv()">Cancelar</button>
                    </form>
                </div>
            </div>

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <!--<script src="../vendor/raphael/raphael.min.js"></script>-->
    <!--<script src="../vendor/morrisjs/morris.min.js"></script>-->
    <!--<script src="../data/morris-data.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>

`)
//line templates/zona.qtpl:268
}

//line templates/zona.qtpl:268
func WriteZonaTemplate(qq422016 qtio422016.Writer, zonas []model.Zona, error string) {
	//line templates/zona.qtpl:268
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/zona.qtpl:268
	StreamZonaTemplate(qw422016, zonas, error)
	//line templates/zona.qtpl:268
	qt422016.ReleaseWriter(qw422016)
//line templates/zona.qtpl:268
}

//line templates/zona.qtpl:268
func ZonaTemplate(zonas []model.Zona, error string) string {
	//line templates/zona.qtpl:268
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/zona.qtpl:268
	WriteZonaTemplate(qb422016, zonas, error)
	//line templates/zona.qtpl:268
	qs422016 := string(qb422016.B)
	//line templates/zona.qtpl:268
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/zona.qtpl:268
	return qs422016
//line templates/zona.qtpl:268
}
